import type { EmphasisAttribute } from './session';

export type EmphasisPresetName = 'default' | 'none';
export type EmphasisPreset = Readonly<Record<EmphasisAttribute, number>>;

export const EMPHASIS_LEVEL_MIN = -4;
export const EMPHASIS_LEVEL_NEUTRAL = 0;
export const EMPHASIS_LEVEL_MAX = 4;
export const EMPHASIS_LEVEL_STEP = 1;
export const EMPHASIS_LEVEL_TICKS = [
  EMPHASIS_LEVEL_MAX,
  EMPHASIS_LEVEL_NEUTRAL,
  EMPHASIS_LEVEL_MIN,
] as const;

export const EMPHASIS_PRESETS = {
  default: {
    'serif': 3,
    'cursive': 2,
    'italic': -2,
    'formal': 2,
    'delicate': 0,
    'playful': 2,
    'legible': 0,
    'thin': -2,
    'angular': 2,
    'artistic': 2,
    'attention-grabbing': 2,
    'attractive': 2,
    'bad': 1,
    'boring': -1,
    'calm': 0,
    'capitals': -2,
    'charming': 2,
    'clumsy': 1,
    'complex': 1,
    'disorderly': 2,
    'display': -2,
    'dramatic': 1,
    'fresh': 0,
    'friendly': 0,
    'gentle': 2,
    'graceful': 2,
    'happy': 1,
    'modern': 2,
    'monospace': -2,
    'pretentious': 2,
    'sharp': 1,
    'sloppy': 1,
    'soft': 0,
    'strong': 1,
    'technical': 0,
    'warm': 1,
    'wide': 2,
  },
  none: {
    'serif': 0,
    'cursive': 0,
    'italic': 0,
    'formal': 0,
    'delicate': 0,
    'playful': 0,
    'legible': 0,
    'thin': 0,
    'angular': 0,
    'artistic': 0,
    'attention-grabbing': 0,
    'attractive': 0,
    'bad': 0,
    'boring': 0,
    'calm': 0,
    'capitals': 0,
    'charming': 0,
    'clumsy': 0,
    'complex': 0,
    'disorderly': 0,
    'display': 0,
    'dramatic': 0,
    'fresh': 0,
    'friendly': 0,
    'gentle': 0,
    'graceful': 0,
    'happy': 0,
    'modern': 0,
    'monospace': 0,
    'pretentious': 0,
    'sharp': 0,
    'sloppy': 0,
    'soft': 0,
    'strong': 0,
    'technical': 0,
    'warm': 0,
    'wide': 0,
  },
} as const satisfies Readonly<Record<EmphasisPresetName, EmphasisPreset>>;
